"""Tests for retrieve.py re-rank + episode filtering.

Pure unit tests — no Qdrant / FalkorDB / Ollama. Operate directly on
``VectorHit`` / ``Episode`` fixtures.
"""

from __future__ import annotations

from pathlib import Path

from code_memory.episodic import Episode
from code_memory.extractor.treesitter import looks_generated
from code_memory.orchestrator.retrieve import (
    ENTRYPOINT_BOOST,
    GENERATED_PENALTY,
    _filter_episodes,
    _is_entrypoint,
    _rerank_code,
)
from code_memory.vector import VectorHit


def _hit(path: str, score: float, *, generated: bool = False) -> VectorHit:
    return VectorHit(
        id=f"id:{path}",
        score=score,
        payload={"path": path, "generated": generated},
    )


# ---------------------------------------------------------------- generated


def test_looks_generated_detects_header(tmp_path: Path) -> None:
    f = tmp_path / "ok.ts"
    f.write_text("/* @generated by openapi-generator */\nexport class X {}\n")
    assert looks_generated(f, f.read_text())


def test_looks_generated_detects_path(tmp_path: Path) -> None:
    p = tmp_path / "api" / "generated" / "client.ts"
    assert looks_generated(p, "export class X {}")


def test_looks_generated_detects_suffix(tmp_path: Path) -> None:
    p = tmp_path / "schema.generated.ts"
    assert looks_generated(p, "export class X {}")


def test_looks_generated_passes_normal_source(tmp_path: Path) -> None:
    p = tmp_path / "src" / "app" / "auth.ts"
    assert not looks_generated(p, "export class AuthService {}")


# ---------------------------------------------------------------- entrypoints


def test_is_entrypoint_known_basenames() -> None:
    assert _is_entrypoint("/repo/src/app/app.config.ts")
    assert _is_entrypoint("/repo/src/app/app.routes.ts")
    assert _is_entrypoint("/repo/src/main.ts")


def test_is_entrypoint_suffix_match() -> None:
    assert _is_entrypoint("/repo/src/app/auth.module.ts")
    assert _is_entrypoint("/repo/src/app/foo.routing.ts")


def test_is_entrypoint_rejects_regular_file() -> None:
    assert not _is_entrypoint("/repo/src/app/auth.service.ts")
    assert not _is_entrypoint(None)


# ---------------------------------------------------------------- rerank


def test_rerank_penalizes_generated() -> None:
    hits = [
        _hit("/r/src/app/auth.service.ts", 0.70),
        _hit("/r/src/api/generated/client.ts", 0.80, generated=True),
    ]
    out = _rerank_code(hits)
    # generated had higher cosine, but penalty flips order
    assert out[0].payload["path"] == "/r/src/app/auth.service.ts"
    assert out[1].score == 0.80 - GENERATED_PENALTY


def test_rerank_boosts_entrypoint() -> None:
    hits = [
        _hit("/r/src/app/auth.service.ts", 0.70),
        _hit("/r/src/app/app.config.ts", 0.68),
    ]
    out = _rerank_code(hits)
    # config gets +0.05 -> 0.73 beats auth.service 0.70
    assert out[0].payload["path"] == "/r/src/app/app.config.ts"
    assert abs(out[0].score - (0.68 + ENTRYPOINT_BOOST)) < 1e-9


def test_rerank_stacks_penalty_and_boost() -> None:
    hits = [
        _hit(
            "/r/src/app/api/generated/app.module.ts",
            0.90,
            generated=True,
        ),
    ]
    out = _rerank_code(hits)
    assert abs(out[0].score - (0.90 - GENERATED_PENALTY + ENTRYPOINT_BOOST)) < 1e-9


def test_rerank_preserves_hit_count() -> None:
    hits = [_hit(f"/r/file{i}.ts", 0.5 - i * 0.01) for i in range(10)]
    assert len(_rerank_code(hits)) == len(hits)


# ---------------------------------------------------------------- episodes


def _ep(ep_id: str, prompt: str, verdict: str | None) -> Episode:
    return Episode(id=ep_id, prompt=prompt, verdict=verdict)


def _ep_hit(ep_id: str, score: float) -> VectorHit:
    return VectorHit(id=ep_id, score=score, payload={})


def test_filter_episodes_drops_idle_by_default() -> None:
    hits = [_ep_hit("a", 0.9), _ep_hit("b", 0.8)]
    eps = [_ep("a", "how is auth handled", "idle"), _ep("b", "fixed login bug", "success")]
    kept_hits, kept_eps = _filter_episodes(
        "different query", hits, eps, limit=5, include_idle=False
    )
    assert [ep.id for ep in kept_eps] == ["b"]
    assert [h.id for h in kept_hits] == ["b"]


def test_filter_episodes_keeps_idle_when_opted_in() -> None:
    hits = [_ep_hit("a", 0.9)]
    eps = [_ep("a", "how is auth handled", "idle")]
    _, kept = _filter_episodes("anything else", hits, eps, limit=5, include_idle=True)
    assert [ep.id for ep in kept] == ["a"]


def test_filter_episodes_dedupes_against_query() -> None:
    hits = [_ep_hit("a", 0.95)]
    eps = [_ep("a", "How is `authentication` handled?", "success")]
    _, kept = _filter_episodes(
        "how is `authentication` handled?",  # same prompt as ep
        hits,
        eps,
        limit=5,
        include_idle=False,
    )
    assert kept == []


def test_filter_episodes_dedupes_internal_duplicates() -> None:
    hits = [_ep_hit("a", 0.9), _ep_hit("b", 0.85), _ep_hit("c", 0.7)]
    eps = [
        _ep("a", "fix the auth bug", "success"),
        _ep("b", "fix   THE auth\tbug", "success"),  # normalized = same as a
        _ep("c", "refactor token storage", "success"),
    ]
    _, kept = _filter_episodes("unrelated", hits, eps, limit=5, include_idle=False)
    assert [ep.id for ep in kept] == ["a", "c"]


def test_filter_episodes_respects_limit() -> None:
    hits = [_ep_hit(str(i), 1.0 - i * 0.01) for i in range(10)]
    eps = [_ep(str(i), f"task number {i}", "success") for i in range(10)]
    _, kept = _filter_episodes("q", hits, eps, limit=3, include_idle=False)
    assert len(kept) == 3
