from __future__ import annotations

import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

from tree_sitter import Language, Node, Parser
from tree_sitter_language_pack import get_language

LANG_BY_EXT: dict[str, str] = {
    ".ts": "typescript",
    ".tsx": "tsx",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".py": "python",
    # .NET ecosystem
    ".cs": "csharp",
    ".cshtml": "razor",
    ".razor": "razor",
    ".vb": "vb",
    ".fs": "fsharp",
    ".fsi": "fsharp",
    ".fsx": "fsharp",
}

SYMBOL_NODE_TYPES = {
    "function_declaration",
    "function_definition",
    "method_definition",
    "class_declaration",
    "class_definition",
    "arrow_function",
    "export_statement",
    # C# / Razor (Razor embeds C#)
    "method_declaration",
    "interface_declaration",
    "struct_declaration",
    "record_declaration",
    "enum_declaration",
    "constructor_declaration",
    "delegate_declaration",
    "property_declaration",
    # VB.NET
    "class_block",
    "module_block",
    "namespace_block",
    # F#
    "function_or_value_defn",
    "type_definition",
    "method_or_prop_defn",
    "named_module",
}

CALL_NODE_TYPES = {
    "call_expression",
    "call",
    "invocation_expression",
    "invocation",  # VB
}

IMPORT_NODE_TYPES = {
    "import_statement",
    "import_from_statement",
    "using_directive",  # C#
    "razor_using_directive",  # Razor
    "imports_statement",  # VB
    "import_decl",  # F#
}


@dataclass
class Symbol:
    name: str
    kind: str
    start_line: int
    end_line: int
    snippet: str
    namespace: str | None = None
    partial: bool = False


@dataclass
class ExtractedFile:
    path: str
    lang: str
    symbols: list[Symbol] = field(default_factory=list)
    imports: list[str] = field(default_factory=list)
    calls: list[str] = field(default_factory=list)
    source: str = ""
    generated: bool = False


@lru_cache(maxsize=16)
def _parser_for(lang: str) -> Parser:
    language: Language = get_language(lang)
    return Parser(language)


def lang_for(path: str | Path) -> str | None:
    return LANG_BY_EXT.get(Path(path).suffix.lower())


MAX_FILE_BYTES = 500_000  # skip files larger than ~500KB (bundles, minified)
MAX_LINE_LEN = 2000  # likely minified if any line is this long
MINIFIED_SNIFF_BYTES = 4096  # bytes to inspect for minified-file heuristic
MINIFIED_AVG_LINE = 200  # avg line length above this in sniff window => minified

# Substrings that, when present in the first ~2KB of a file, mark it as
# auto-generated. These are case-insensitive contains checks.
GENERATED_HEADER_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "code generated by",
    "do not edit",
    "this file was generated",
    "generated by openapi",
    "generated by swagger",
    "generated by ng-openapi-gen",
    "generated by openapi-generator",
)

# Path segments / suffixes that indicate generated output.
_GENERATED_PATH_PARTS = ("generated", "__generated__", "openapi-gen", "swagger-gen")
_GENERATED_PATH_SUFFIXES = (".generated.ts", ".generated.js", ".g.ts", ".g.dart")


def _has_generated_header(sample: str) -> bool:
    lower = sample[:2048].lower()
    return any(m in lower for m in GENERATED_HEADER_MARKERS)


def _has_generated_path(path: Path) -> bool:
    parts_lower = {part.lower() for part in path.parts}
    if any(p in parts_lower for p in _GENERATED_PATH_PARTS):
        return True
    name_lower = path.name.lower()
    return any(name_lower.endswith(suf) for suf in _GENERATED_PATH_SUFFIXES)


def looks_generated(path: str | Path, sample: str) -> bool:
    """Detect auto-generated code by path heuristics or header markers."""
    p = Path(path)
    return _has_generated_path(p) or _has_generated_header(sample)


def looks_minified(sample: str) -> bool:
    """Detect minified / pre-bundled JS without parsing.

    Triggers when:
    - the sniffed window has no newline (one giant line), or
    - the average line length within the sniffed window exceeds
      ``MINIFIED_AVG_LINE``, or
    - any line in the sniffed window exceeds ``MAX_LINE_LEN``.

    Vite/webpack dep caches and minified bundles all match at least one.
    """
    if not sample:
        return False
    if "\n" not in sample:
        return True
    lines = sample.splitlines()
    if any(len(line) > MAX_LINE_LEN for line in lines):
        return True
    avg = len(sample) / max(len(lines), 1)
    return avg > MINIFIED_AVG_LINE


def extract_file(path: str | Path) -> ExtractedFile | None:
    p = Path(path)
    lang = lang_for(p)
    if lang is None:
        return None
    try:
        size = p.stat().st_size
    except OSError:
        return None
    if size > MAX_FILE_BYTES:
        return None
    raw = p.read_bytes()
    # Strip a UTF-8 BOM if present so tree-sitter's byte offsets line up
    # with our slicing buffer. Some Windows-authored C# files ship one.
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    source = raw.decode("utf-8", errors="replace")
    if looks_minified(source[:MINIFIED_SNIFF_BYTES]):
        return None  # minified / bundled
    parser = _parser_for(lang)
    tree = parser.parse(raw)
    root = tree.root_node
    ex = ExtractedFile(
        path=str(p.resolve()),
        lang=lang,
        source=source,
        generated=looks_generated(p, source),
    )
    _walk(root, raw, ex, ns_stack=[])
    return ex


# C# block-scoped ``namespace Foo { ... }``. Pushed while walking the
# block's children and popped on exit.
_BLOCK_NAMESPACE_NODE_TYPES = {"namespace_declaration"}

# C# 10 ``namespace Foo;`` (file-scoped). One per file by spec; applies
# to *everything after it*. We push without popping.
_FILE_SCOPED_NAMESPACE_NODE_TYPES = {"file_scoped_namespace_declaration"}

# Symbol kinds that can carry a ``partial`` modifier in C#. Partial
# classes / structs / interfaces / records get merged into a single
# logical entity in the graph; non-partial symbols stay file-scoped.
_PARTIAL_CAPABLE_KINDS = {
    "class_declaration",
    "struct_declaration",
    "interface_declaration",
    "record_declaration",
}


def _is_partial_modifier(node: Node, source: bytes) -> bool:
    """``True`` when this is a ``modifier`` node carrying ``partial``."""
    if node.type != "modifier":
        return False
    text = _slice(source, node).strip()
    return text == "partial"


def _has_partial_modifier(node: Node, source: bytes) -> bool:
    return any(_is_partial_modifier(c, source) for c in node.children)


def _namespace_name(node: Node, source: bytes) -> str | None:
    """Return the dotted name of a C# namespace declaration."""
    for child in node.children:
        if child.type in {"qualified_name", "identifier"}:
            return _slice(source, child)
    return None


def _walk(
    node: Node,
    source: bytes,
    ex: ExtractedFile,
    ns_stack: list[str],
) -> None:
    t = node.type
    pushed_ns = False
    if t in _BLOCK_NAMESPACE_NODE_TYPES:
        ns = _namespace_name(node, source)
        if ns:
            ns_stack.append(ns)
            pushed_ns = True
    elif t in _FILE_SCOPED_NAMESPACE_NODE_TYPES:
        # C# 10 file-scoped namespace scopes the rest of the file.
        # Push and never pop within this walk — there is at most one.
        ns = _namespace_name(node, source)
        if ns:
            ns_stack.append(ns)

    if t in SYMBOL_NODE_TYPES:
        name = _symbol_name(node, source)
        if name:
            partial = (
                t in _PARTIAL_CAPABLE_KINDS and _has_partial_modifier(node, source)
            )
            ex.symbols.append(
                Symbol(
                    name=name,
                    kind=t,
                    start_line=node.start_point[0] + 1,
                    end_line=node.end_point[0] + 1,
                    snippet=_slice(source, node),
                    namespace=".".join(ns_stack) if ns_stack else None,
                    partial=partial,
                )
            )
    elif t in IMPORT_NODE_TYPES:
        mod = _import_module(node, source)
        if mod:
            ex.imports.append(mod)
    elif t in CALL_NODE_TYPES:
        callee = _callee_name(node, source)
        if callee:
            ex.calls.append(callee)

    for child in node.children:
        _walk(child, source, ex, ns_stack)

    if pushed_ns:
        ns_stack.pop()


def _slice(source: bytes, node: Node) -> str:
    """Return UTF-8 text at the node's byte range.

    Tree-sitter reports byte offsets into the parsed buffer, not
    character offsets. Slicing a Python ``str`` with those offsets
    silently chops identifiers on files that contain any non-ASCII
    bytes (e.g. French C# with accents). Slicing ``bytes`` then
    decoding fixes the off-by-many-bytes drift.
    """
    return source[node.start_byte : node.end_byte].decode("utf-8", errors="replace")


_FSHARP_DEEP_NAME_NODES = {
    "function_or_value_defn",
    "type_definition",
}


def _first_identifier_deep(node: Node, source: bytes) -> str | None:
    """BFS for the first identifier-bearing token inside ``node``."""
    queue: list[Node] = [node]
    while queue:
        current = queue.pop(0)
        for child in current.children:
            if child.type in {"identifier", "type_identifier"}:
                return _slice(source, child)
            queue.append(child)
    return None


def _symbol_name(node: Node, source: bytes) -> str | None:
    name = node.child_by_field_name("name")
    if name is not None:
        return _slice(source, name)
    if node.type in _FSHARP_DEEP_NAME_NODES:
        return _first_identifier_deep(node, source)
    for child in node.children:
        if child.type in {"identifier", "type_identifier"}:
            return _slice(source, child)
    return None


def _import_module(node: Node, source: bytes) -> str | None:
    for child in node.children:
        if child.type in {
            "string",
            "string_fragment",
            "dotted_name",
            "module_name",
            "qualified_name",
            "namespace_name",  # VB
            "long_identifier",  # F#
            "identifier",
        }:
            return _slice(source, child).strip("'\"")
    return None


# Callees that are stdlib / framework / RxJS / Angular DI built-ins.
# Filtered at extract time so they never enter the graph as CALLS edges;
# they pollute "who calls X" queries with high-frequency noise.
CALLEE_STOPLIST: frozenset[str] = frozenset(
    {
        # JS builtins
        "console", "JSON", "Math", "Object", "Array", "Promise", "Number",
        "String", "Boolean", "Date", "RegExp", "Symbol", "Map", "Set",
        "parseInt", "parseFloat", "isNaN", "isFinite",
        "setTimeout", "setInterval", "clearTimeout", "clearInterval",
        "fetch", "structuredClone", "queueMicrotask",
        # Angular DI / lifecycle
        "inject", "Injectable", "Component", "Directive", "Pipe", "NgModule",
        "Input", "Output", "ViewChild", "ContentChild", "HostListener",
        "HostBinding",
        # RxJS operators commonly chained via .pipe()
        "pipe", "subscribe", "map", "filter", "tap", "switchMap", "mergeMap",
        "concatMap", "exhaustMap", "catchError", "take", "takeUntil", "first",
        "of", "from", "EMPTY", "throwError", "combineLatest", "forkJoin",
        "BehaviorSubject", "Subject", "ReplaySubject",
        # Generic test helpers
        "describe", "it", "test", "expect", "beforeEach", "afterEach",
        "beforeAll", "afterAll", "jest", "vi", "spyOn",
    }
)


def _callee_name(node: Node, source: bytes) -> str | None:
    """Return the last identifier of a call expression's callee.

    For ``foo()`` → ``foo``. For ``this.svc.method()`` → ``method``.
    For ``a.b.c()`` → ``c``. Computed (``a[b]()``) and chained
    (``f()()``) callees collapse to ``None`` — too ambiguous to resolve.

    Returns ``None`` for callees in :data:`CALLEE_STOPLIST` so they don't
    enter the graph as noise.
    """
    fn = node.child_by_field_name("function") or node.child_by_field_name("callee")
    if fn is None and node.children:
        fn = node.children[0]
    if fn is None:
        return None
    raw = _slice(source, fn).split("(")[0].strip()
    name = _last_identifier(raw)
    if name is None or name in CALLEE_STOPLIST:
        return None
    return name


_IDENT_RE = re.compile(r"[A-Za-z_$][\w$]*")


def _last_identifier(expr: str) -> str | None:
    """Extract the trailing identifier from a (possibly chained) expression.

    ``this.foo.bar``     → ``bar``
    ``MyClass.staticFn`` → ``staticFn``
    ``foo``              → ``foo``
    ``arr[i]``           → ``None`` (computed)
    ``f()``              → ``None`` (chained call; shouldn't normally hit)
    """
    # Reject anything with brackets or calls in the trailing position.
    if expr.endswith("]") or expr.endswith(")"):
        return None
    parts = expr.split(".")
    last = parts[-1].strip()
    if not last:
        return None
    m = _IDENT_RE.fullmatch(last)
    return m.group(0) if m else None


DEFAULT_IGNORE_DIRS: tuple[str, ...] = (
    ".git",
    "node_modules",
    ".venv",
    "venv",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "out",
    "coverage",
    ".turbo",
    ".cache",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "target",
    # Angular / Vite / Nx / Yarn / Parcel / SvelteKit caches and tarballs
    ".angular",
    ".nx",
    ".yarn",
    ".parcel-cache",
    ".svelte-kit",
    "bower_components",
    "vendor",
    "tmp",
    # .NET build output / IDE caches
    "bin",
    "obj",
    "packages",
    "TestResults",
    ".vs",
    "artifacts",
)


class Extractor:
    """Convenience wrapper to walk a directory."""

    def __init__(
        self,
        ignore_dirs: tuple[str, ...] = DEFAULT_IGNORE_DIRS,
        *,
        respect_gitignore: bool = True,
    ) -> None:
        self.ignore_dirs = ignore_dirs
        self.respect_gitignore = respect_gitignore

    def walk(self, root: str | Path):
        from .gitignore import GitignoreMatcher

        root_path = Path(root).resolve()
        matcher = (
            GitignoreMatcher.from_root(root_path) if self.respect_gitignore else None
        )
        ignore_set = set(self.ignore_dirs)
        for p in root_path.rglob("*"):
            if not p.is_file():
                continue
            if any(part in ignore_set for part in p.parts):
                continue
            if matcher is not None and matcher.match(p, is_dir=False):
                continue
            ex = extract_file(p)
            if ex is not None:
                yield ex
